[package]
name = "sqlite_varint"
version = "0.1.0"
authors = ["Midas Lambrichts <midaslamb@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "read_benchmark"
harness = false
